FROM python:3.7

ADD . /src
RUN mkdir -p /data
RUN pip3 install  --no-cache-dir -r /src/requirements.txt

WORKDIR /src/frontend
ENV DATADIR=/data FLASK_APP=web
EXPOSE 8080
CMD gunicorn -b :8080 web:app --access-logfile -