FROM python:3.7

ADD operator /src/


ADD run-operator.sh /usr/local/bin

RUN mkdir -p /data

ENV DATADIR /data

RUN pip3 install  --no-cache-dir -r /src/requirements.txt

CMD /usr/local/bin/run-operator.sh
