---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collectlogs
  namespace: %NAMESPACE%
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-collectlogs
subjects:
  - kind: ServiceAccount
    name: collectlogs
    namespace: %NAMESPACE%
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
