---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collectlogs
  namespace: %NAMESPACE%

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: %NAMESPACE%
  name: collectlogs-role
rules:
  - apiGroups: [tekton.dev]
    resources: [pipelineruns]
    verbs: [list, watch, patch, get]

  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-collectlogs
subjects:
  - kind: ServiceAccount
    name: collectlogs
    namespace: %NAMESPACE%
roleRef:
  kind: Role
  name: collectlogs-role
  apiGroup: rbac.authorization.k8s.io
